-- CreateTable
CREATE TABLE "Quote" (
    "id" SERIAL NOT NULL,
    "status" INTEGER NOT NULL DEFAULT 1,
    "price" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "clientId" INTEGER,
    "fullName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phoneNumber" TEXT NOT NULL,
    "isCustom" BOOLEAN NOT NULL DEFAULT false,
    "neonTexts" JSONB,
    "alignment" TEXT,
    "size" JSONB,
    "notes" TEXT,
    "waterproof" BOOLEAN,
    "backboardStyle" TEXT,
    "backboardColor" TEXT,
    "wallMountingKit" TEXT,
    "signMountingKit" BOOLEAN,
    "remoteControl" BOOLEAN,
    "width" DOUBLE PRECISION,
    "height" DOUBLE PRECISION,
    "images" TEXT[],
    "sizeUnit" TEXT,
    "descriptionQuote" TEXT,
    "descriptionPrice" DOUBLE PRECISION,
    "descriptionSuggestedPrice" DOUBLE PRECISION,
    "widthQuote" DOUBLE PRECISION,
    "heightQuote" DOUBLE PRECISION,
    "sizePrice" DOUBLE PRECISION,
    "sizeSuggestedPrice" DOUBLE PRECISION,
    "waterproofQuote" BOOLEAN,
    "waterproofPrice" DOUBLE PRECISION,
    "waterproofSuggestedPrice" DOUBLE PRECISION,
    "backboardStyleQuote" TEXT,
    "backboardStylePrice" DOUBLE PRECISION,
    "backboardStyleSuggestedPrice" DOUBLE PRECISION,
    "backboardColorQuote" TEXT,
    "backboardColorPrice" DOUBLE PRECISION,
    "backboardColorSuggestedPrice" DOUBLE PRECISION,
    "mockUpQuote" TEXT[],
    "mockUpPrice" DOUBLE PRECISION,
    "mockUpSuggestedPrice" DOUBLE PRECISION,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Quote_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Quote" ADD CONSTRAINT "Quote_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
